<?php
/**
 * XBSettlementFlowSetupStep
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DeveloperayoFireblocksLaravel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DeveloperayoFireblocksLaravel\Model;

use \ArrayAccess;
use \DeveloperayoFireblocksLaravel\ObjectSerializer;

/**
 * XBSettlementFlowSetupStep Class Doc Comment
 *
 * @category Class
 * @package  DeveloperayoFireblocksLaravel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class XBSettlementFlowSetupStep implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'XBSettlementFlowSetupStep';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'string',
        'input_amount' => '\DeveloperayoFireblocksLaravel\Model\XBSettlementAsset',
        'output_amount' => '\DeveloperayoFireblocksLaravel\Model\XBSettlementAsset',
        'estimated_fee_amount' => '\DeveloperayoFireblocksLaravel\Model\XBSettlementAsset',
        'estimated_time' => 'float',
        'is_sign_required' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => null,
        'input_amount' => null,
        'output_amount' => null,
        'estimated_fee_amount' => null,
        'estimated_time' => null,
        'is_sign_required' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_id' => false,
        'input_amount' => false,
        'output_amount' => false,
        'estimated_fee_amount' => false,
        'estimated_time' => false,
        'is_sign_required' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountId',
        'input_amount' => 'inputAmount',
        'output_amount' => 'outputAmount',
        'estimated_fee_amount' => 'estimatedFeeAmount',
        'estimated_time' => 'estimatedTime',
        'is_sign_required' => 'isSignRequired'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'input_amount' => 'setInputAmount',
        'output_amount' => 'setOutputAmount',
        'estimated_fee_amount' => 'setEstimatedFeeAmount',
        'estimated_time' => 'setEstimatedTime',
        'is_sign_required' => 'setIsSignRequired'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'input_amount' => 'getInputAmount',
        'output_amount' => 'getOutputAmount',
        'estimated_fee_amount' => 'getEstimatedFeeAmount',
        'estimated_time' => 'getEstimatedTime',
        'is_sign_required' => 'getIsSignRequired'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('input_amount', $data ?? [], null);
        $this->setIfExists('output_amount', $data ?? [], null);
        $this->setIfExists('estimated_fee_amount', $data ?? [], null);
        $this->setIfExists('estimated_time', $data ?? [], null);
        $this->setIfExists('is_sign_required', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if ($this->container['input_amount'] === null) {
            $invalidProperties[] = "'input_amount' can't be null";
        }
        if ($this->container['output_amount'] === null) {
            $invalidProperties[] = "'output_amount' can't be null";
        }
        if ($this->container['estimated_fee_amount'] === null) {
            $invalidProperties[] = "'estimated_fee_amount' can't be null";
        }
        if ($this->container['estimated_time'] === null) {
            $invalidProperties[] = "'estimated_time' can't be null";
        }
        if ($this->container['is_sign_required'] === null) {
            $invalidProperties[] = "'is_sign_required' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets input_amount
     *
     * @return \DeveloperayoFireblocksLaravel\Model\XBSettlementAsset
     */
    public function getInputAmount()
    {
        return $this->container['input_amount'];
    }

    /**
     * Sets input_amount
     *
     * @param \DeveloperayoFireblocksLaravel\Model\XBSettlementAsset $input_amount input_amount
     *
     * @return self
     */
    public function setInputAmount($input_amount)
    {
        if (is_null($input_amount)) {
            throw new \InvalidArgumentException('non-nullable input_amount cannot be null');
        }
        $this->container['input_amount'] = $input_amount;

        return $this;
    }

    /**
     * Gets output_amount
     *
     * @return \DeveloperayoFireblocksLaravel\Model\XBSettlementAsset
     */
    public function getOutputAmount()
    {
        return $this->container['output_amount'];
    }

    /**
     * Sets output_amount
     *
     * @param \DeveloperayoFireblocksLaravel\Model\XBSettlementAsset $output_amount output_amount
     *
     * @return self
     */
    public function setOutputAmount($output_amount)
    {
        if (is_null($output_amount)) {
            throw new \InvalidArgumentException('non-nullable output_amount cannot be null');
        }
        $this->container['output_amount'] = $output_amount;

        return $this;
    }

    /**
     * Gets estimated_fee_amount
     *
     * @return \DeveloperayoFireblocksLaravel\Model\XBSettlementAsset
     */
    public function getEstimatedFeeAmount()
    {
        return $this->container['estimated_fee_amount'];
    }

    /**
     * Sets estimated_fee_amount
     *
     * @param \DeveloperayoFireblocksLaravel\Model\XBSettlementAsset $estimated_fee_amount estimated_fee_amount
     *
     * @return self
     */
    public function setEstimatedFeeAmount($estimated_fee_amount)
    {
        if (is_null($estimated_fee_amount)) {
            throw new \InvalidArgumentException('non-nullable estimated_fee_amount cannot be null');
        }
        $this->container['estimated_fee_amount'] = $estimated_fee_amount;

        return $this;
    }

    /**
     * Gets estimated_time
     *
     * @return float
     */
    public function getEstimatedTime()
    {
        return $this->container['estimated_time'];
    }

    /**
     * Sets estimated_time
     *
     * @param float $estimated_time The estimated time for executing the step.
     *
     * @return self
     */
    public function setEstimatedTime($estimated_time)
    {
        if (is_null($estimated_time)) {
            throw new \InvalidArgumentException('non-nullable estimated_time cannot be null');
        }
        $this->container['estimated_time'] = $estimated_time;

        return $this;
    }

    /**
     * Gets is_sign_required
     *
     * @return bool
     */
    public function getIsSignRequired()
    {
        return $this->container['is_sign_required'];
    }

    /**
     * Sets is_sign_required
     *
     * @param bool $is_sign_required Whether or not signing is required for executing the step.
     *
     * @return self
     */
    public function setIsSignRequired($is_sign_required)
    {
        if (is_null($is_sign_required)) {
            throw new \InvalidArgumentException('non-nullable is_sign_required cannot be null');
        }
        $this->container['is_sign_required'] = $is_sign_required;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


