<?php
/**
 * ContractsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Developerayo\FireblocksLaravel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Developerayo\FireblocksLaravel\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Developerayo\FireblocksLaravel\ApiException;
use Developerayo\FireblocksLaravel\Configuration;
use Developerayo\FireblocksLaravel\FormDataProcessor;
use Developerayo\FireblocksLaravel\HeaderSelector;
use Developerayo\FireblocksLaravel\ObjectSerializer;

/**
 * ContractsApi Class Doc Comment
 *
 * @category Class
 * @package  Developerayo\FireblocksLaravel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContractsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'contractsContractIdAssetIdDelete' => [
            'application/json',
        ],
        'contractsContractIdAssetIdGet' => [
            'application/json',
        ],
        'contractsContractIdAssetIdPost' => [
            'application/json',
        ],
        'contractsContractIdDelete' => [
            'application/json',
        ],
        'contractsContractIdGet' => [
            'application/json',
        ],
        'contractsGet' => [
            'application/json',
        ],
        'contractsPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation contractsContractIdAssetIdDelete
     *
     * Delete a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdDelete'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function contractsContractIdAssetIdDelete($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdDelete'][0])
    {
        $this->contractsContractIdAssetIdDeleteWithHttpInfo($contractId, $assetId, $contentType);
    }

    /**
     * Operation contractsContractIdAssetIdDeleteWithHttpInfo
     *
     * Delete a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdDelete'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsContractIdAssetIdDeleteWithHttpInfo($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdDelete'][0])
    {
        $request = $this->contractsContractIdAssetIdDeleteRequest($contractId, $assetId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsContractIdAssetIdDeleteAsync
     *
     * Delete a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdAssetIdDeleteAsync($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdDelete'][0])
    {
        return $this->contractsContractIdAssetIdDeleteAsyncWithHttpInfo($contractId, $assetId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsContractIdAssetIdDeleteAsyncWithHttpInfo
     *
     * Delete a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdAssetIdDeleteAsyncWithHttpInfo($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdDelete'][0])
    {
        $returnType = '';
        $request = $this->contractsContractIdAssetIdDeleteRequest($contractId, $assetId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsContractIdAssetIdDelete'
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsContractIdAssetIdDeleteRequest($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdDelete'][0])
    {

        // verify the required parameter 'contractId' is set
        if ($contractId === null || (is_array($contractId) && count($contractId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contractId when calling contractsContractIdAssetIdDelete'
            );
        }
        
        // verify the required parameter 'assetId' is set
        if ($assetId === null || (is_array($assetId) && count($assetId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $assetId when calling contractsContractIdAssetIdDelete'
            );
        }
        

        $resourcePath = '/contracts/{contractId}/{assetId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contractId !== null) {
            $resourcePath = str_replace(
                '{' . 'contractId' . '}',
                ObjectSerializer::toPathValue($contractId),
                $resourcePath
            );
        }
        // path params
        if ($assetId !== null) {
            $resourcePath = str_replace(
                '{' . 'assetId' . '}',
                ObjectSerializer::toPathValue($assetId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contractsContractIdAssetIdGet
     *
     * Find a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\ExternalWalletAsset|\Developerayo\FireblocksLaravel\Models\Error
     */
    public function contractsContractIdAssetIdGet($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdGet'][0])
    {
        list($response) = $this->contractsContractIdAssetIdGetWithHttpInfo($contractId, $assetId, $contentType);
        return $response;
    }

    /**
     * Operation contractsContractIdAssetIdGetWithHttpInfo
     *
     * Find a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\ExternalWalletAsset|\Developerayo\FireblocksLaravel\Models\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsContractIdAssetIdGetWithHttpInfo($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdGet'][0])
    {
        $request = $this->contractsContractIdAssetIdGetRequest($contractId, $assetId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsContractIdAssetIdGetAsync
     *
     * Find a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdAssetIdGetAsync($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdGet'][0])
    {
        return $this->contractsContractIdAssetIdGetAsyncWithHttpInfo($contractId, $assetId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsContractIdAssetIdGetAsyncWithHttpInfo
     *
     * Find a contract asset
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdAssetIdGetAsyncWithHttpInfo($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdGet'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset';
        $request = $this->contractsContractIdAssetIdGetRequest($contractId, $assetId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsContractIdAssetIdGet'
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsContractIdAssetIdGetRequest($contractId, $assetId, string $contentType = self::contentTypes['contractsContractIdAssetIdGet'][0])
    {

        // verify the required parameter 'contractId' is set
        if ($contractId === null || (is_array($contractId) && count($contractId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contractId when calling contractsContractIdAssetIdGet'
            );
        }
        
        // verify the required parameter 'assetId' is set
        if ($assetId === null || (is_array($assetId) && count($assetId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $assetId when calling contractsContractIdAssetIdGet'
            );
        }
        

        $resourcePath = '/contracts/{contractId}/{assetId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contractId !== null) {
            $resourcePath = str_replace(
                '{' . 'contractId' . '}',
                ObjectSerializer::toPathValue($contractId),
                $resourcePath
            );
        }
        // path params
        if ($assetId !== null) {
            $resourcePath = str_replace(
                '{' . 'assetId' . '}',
                ObjectSerializer::toPathValue($assetId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contractsContractIdAssetIdPost
     *
     * Add an asset to a contract
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to add (required)
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsContractIdAssetIdPostRequest|null $contractsContractIdAssetIdPostRequest contractsContractIdAssetIdPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdPost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\ExternalWalletAsset|\Developerayo\FireblocksLaravel\Models\Error
     */
    public function contractsContractIdAssetIdPost($contractId, $assetId, $contractsContractIdAssetIdPostRequest = null, string $contentType = self::contentTypes['contractsContractIdAssetIdPost'][0])
    {
        list($response) = $this->contractsContractIdAssetIdPostWithHttpInfo($contractId, $assetId, $contractsContractIdAssetIdPostRequest, $contentType);
        return $response;
    }

    /**
     * Operation contractsContractIdAssetIdPostWithHttpInfo
     *
     * Add an asset to a contract
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to add (required)
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsContractIdAssetIdPostRequest|null $contractsContractIdAssetIdPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdPost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\ExternalWalletAsset|\Developerayo\FireblocksLaravel\Models\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsContractIdAssetIdPostWithHttpInfo($contractId, $assetId, $contractsContractIdAssetIdPostRequest = null, string $contentType = self::contentTypes['contractsContractIdAssetIdPost'][0])
    {
        $request = $this->contractsContractIdAssetIdPostRequest($contractId, $assetId, $contractsContractIdAssetIdPostRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsContractIdAssetIdPostAsync
     *
     * Add an asset to a contract
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to add (required)
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsContractIdAssetIdPostRequest|null $contractsContractIdAssetIdPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdAssetIdPostAsync($contractId, $assetId, $contractsContractIdAssetIdPostRequest = null, string $contentType = self::contentTypes['contractsContractIdAssetIdPost'][0])
    {
        return $this->contractsContractIdAssetIdPostAsyncWithHttpInfo($contractId, $assetId, $contractsContractIdAssetIdPostRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsContractIdAssetIdPostAsyncWithHttpInfo
     *
     * Add an asset to a contract
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to add (required)
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsContractIdAssetIdPostRequest|null $contractsContractIdAssetIdPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdAssetIdPostAsyncWithHttpInfo($contractId, $assetId, $contractsContractIdAssetIdPostRequest = null, string $contentType = self::contentTypes['contractsContractIdAssetIdPost'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\ExternalWalletAsset';
        $request = $this->contractsContractIdAssetIdPostRequest($contractId, $assetId, $contractsContractIdAssetIdPostRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsContractIdAssetIdPost'
     *
     * @param  string $contractId The ID of the contract (required)
     * @param  string $assetId The ID of the asset to add (required)
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsContractIdAssetIdPostRequest|null $contractsContractIdAssetIdPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdAssetIdPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsContractIdAssetIdPostRequest($contractId, $assetId, $contractsContractIdAssetIdPostRequest = null, string $contentType = self::contentTypes['contractsContractIdAssetIdPost'][0])
    {

        // verify the required parameter 'contractId' is set
        if ($contractId === null || (is_array($contractId) && count($contractId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contractId when calling contractsContractIdAssetIdPost'
            );
        }

        // verify the required parameter 'assetId' is set
        if ($assetId === null || (is_array($assetId) && count($assetId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $assetId when calling contractsContractIdAssetIdPost'
            );
        }



        $resourcePath = '/contracts/{contractId}/{assetId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contractId !== null) {
            $resourcePath = str_replace(
                '{' . 'contractId' . '}',
                ObjectSerializer::toPathValue($contractId),
                $resourcePath
            );
        }
        // path params
        if ($assetId !== null) {
            $resourcePath = str_replace(
                '{' . 'assetId' . '}',
                ObjectSerializer::toPathValue($assetId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($contractsContractIdAssetIdPostRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($contractsContractIdAssetIdPostRequest));
            } else {
                $httpBody = $contractsContractIdAssetIdPostRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contractsContractIdDelete
     *
     * Delete a contract
     *
     * @param  string $contractId The ID of the contract to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdDelete'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function contractsContractIdDelete($contractId, string $contentType = self::contentTypes['contractsContractIdDelete'][0])
    {
        $this->contractsContractIdDeleteWithHttpInfo($contractId, $contentType);
    }

    /**
     * Operation contractsContractIdDeleteWithHttpInfo
     *
     * Delete a contract
     *
     * @param  string $contractId The ID of the contract to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdDelete'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsContractIdDeleteWithHttpInfo($contractId, string $contentType = self::contentTypes['contractsContractIdDelete'][0])
    {
        $request = $this->contractsContractIdDeleteRequest($contractId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsContractIdDeleteAsync
     *
     * Delete a contract
     *
     * @param  string $contractId The ID of the contract to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdDeleteAsync($contractId, string $contentType = self::contentTypes['contractsContractIdDelete'][0])
    {
        return $this->contractsContractIdDeleteAsyncWithHttpInfo($contractId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsContractIdDeleteAsyncWithHttpInfo
     *
     * Delete a contract
     *
     * @param  string $contractId The ID of the contract to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdDeleteAsyncWithHttpInfo($contractId, string $contentType = self::contentTypes['contractsContractIdDelete'][0])
    {
        $returnType = '';
        $request = $this->contractsContractIdDeleteRequest($contractId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsContractIdDelete'
     *
     * @param  string $contractId The ID of the contract to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsContractIdDeleteRequest($contractId, string $contentType = self::contentTypes['contractsContractIdDelete'][0])
    {

        // verify the required parameter 'contractId' is set
        if ($contractId === null || (is_array($contractId) && count($contractId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contractId when calling contractsContractIdDelete'
            );
        }
        

        $resourcePath = '/contracts/{contractId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contractId !== null) {
            $resourcePath = str_replace(
                '{' . 'contractId' . '}',
                ObjectSerializer::toPathValue($contractId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contractsContractIdGet
     *
     * Find a specific contract
     *
     * @param  string $contractId The ID of the contract to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\UnmanagedWallet|\Developerayo\FireblocksLaravel\Models\Error
     */
    public function contractsContractIdGet($contractId, string $contentType = self::contentTypes['contractsContractIdGet'][0])
    {
        list($response) = $this->contractsContractIdGetWithHttpInfo($contractId, $contentType);
        return $response;
    }

    /**
     * Operation contractsContractIdGetWithHttpInfo
     *
     * Find a specific contract
     *
     * @param  string $contractId The ID of the contract to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\UnmanagedWallet|\Developerayo\FireblocksLaravel\Models\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsContractIdGetWithHttpInfo($contractId, string $contentType = self::contentTypes['contractsContractIdGet'][0])
    {
        $request = $this->contractsContractIdGetRequest($contractId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsContractIdGetAsync
     *
     * Find a specific contract
     *
     * @param  string $contractId The ID of the contract to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdGetAsync($contractId, string $contentType = self::contentTypes['contractsContractIdGet'][0])
    {
        return $this->contractsContractIdGetAsyncWithHttpInfo($contractId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsContractIdGetAsyncWithHttpInfo
     *
     * Find a specific contract
     *
     * @param  string $contractId The ID of the contract to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsContractIdGetAsyncWithHttpInfo($contractId, string $contentType = self::contentTypes['contractsContractIdGet'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet';
        $request = $this->contractsContractIdGetRequest($contractId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsContractIdGet'
     *
     * @param  string $contractId The ID of the contract to return (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsContractIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsContractIdGetRequest($contractId, string $contentType = self::contentTypes['contractsContractIdGet'][0])
    {

        // verify the required parameter 'contractId' is set
        if ($contractId === null || (is_array($contractId) && count($contractId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contractId when calling contractsContractIdGet'
            );
        }
        

        $resourcePath = '/contracts/{contractId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contractId !== null) {
            $resourcePath = str_replace(
                '{' . 'contractId' . '}',
                ObjectSerializer::toPathValue($contractId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contractsGet
     *
     * List contracts
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\UnmanagedWallet[]|\Developerayo\FireblocksLaravel\Models\Error
     */
    public function contractsGet(string $contentType = self::contentTypes['contractsGet'][0])
    {
        list($response) = $this->contractsGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation contractsGetWithHttpInfo
     *
     * List contracts
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\UnmanagedWallet[]|\Developerayo\FireblocksLaravel\Models\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsGetWithHttpInfo(string $contentType = self::contentTypes['contractsGet'][0])
    {
        $request = $this->contractsGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet[]',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsGetAsync
     *
     * List contracts
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsGetAsync(string $contentType = self::contentTypes['contractsGet'][0])
    {
        return $this->contractsGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsGetAsyncWithHttpInfo
     *
     * List contracts
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsGetAsyncWithHttpInfo(string $contentType = self::contentTypes['contractsGet'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet[]';
        $request = $this->contractsGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsGetRequest(string $contentType = self::contentTypes['contractsGet'][0])
    {


        $resourcePath = '/contracts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['*/*', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contractsPost
     *
     * Create a contract
     *
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsPostRequest|null $contractsPostRequest contractsPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsPost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\UnmanagedWallet|\Developerayo\FireblocksLaravel\Models\Error
     */
    public function contractsPost($contractsPostRequest = null, string $contentType = self::contentTypes['contractsPost'][0])
    {
        list($response) = $this->contractsPostWithHttpInfo($contractsPostRequest, $contentType);
        return $response;
    }

    /**
     * Operation contractsPostWithHttpInfo
     *
     * Create a contract
     *
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsPostRequest|null $contractsPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsPost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\UnmanagedWallet|\Developerayo\FireblocksLaravel\Models\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function contractsPostWithHttpInfo($contractsPostRequest = null, string $contentType = self::contentTypes['contractsPost'][0])
    {
        $request = $this->contractsPostRequest($contractsPostRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation contractsPostAsync
     *
     * Create a contract
     *
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsPostRequest|null $contractsPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsPostAsync($contractsPostRequest = null, string $contentType = self::contentTypes['contractsPost'][0])
    {
        return $this->contractsPostAsyncWithHttpInfo($contractsPostRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contractsPostAsyncWithHttpInfo
     *
     * Create a contract
     *
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsPostRequest|null $contractsPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contractsPostAsyncWithHttpInfo($contractsPostRequest = null, string $contentType = self::contentTypes['contractsPost'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\UnmanagedWallet';
        $request = $this->contractsPostRequest($contractsPostRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contractsPost'
     *
     * @param  \Developerayo\FireblocksLaravel\Models\ContractsPostRequest|null $contractsPostRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contractsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contractsPostRequest($contractsPostRequest = null, string $contentType = self::contentTypes['contractsPost'][0])
    {



        $resourcePath = '/contracts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['*/*', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($contractsPostRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($contractsPostRequest));
            } else {
                $httpBody = $contractsPostRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
