<?php
/**
 * PaymentsPayoutApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Developerayo\FireblocksLaravel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Developerayo\FireblocksLaravel\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Developerayo\FireblocksLaravel\ApiException;
use Developerayo\FireblocksLaravel\Configuration;
use Developerayo\FireblocksLaravel\FormDataProcessor;
use Developerayo\FireblocksLaravel\HeaderSelector;
use Developerayo\FireblocksLaravel\ObjectSerializer;

/**
 * PaymentsPayoutApi Class Doc Comment
 *
 * @category Class
 * @package  Developerayo\FireblocksLaravel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsPayoutApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'paymentsPayoutPayoutIdActionsExecutePost' => [
            'application/json',
        ],
        'paymentsPayoutPayoutIdGet' => [
            'application/json',
        ],
        'paymentsPayoutPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation paymentsPayoutPayoutIdActionsExecutePost
     *
     * Execute a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\DispatchPayoutResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse
     */
    public function paymentsPayoutPayoutIdActionsExecutePost($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'][0])
    {
        list($response) = $this->paymentsPayoutPayoutIdActionsExecutePostWithHttpInfo($payoutId, $contentType);
        return $response;
    }

    /**
     * Operation paymentsPayoutPayoutIdActionsExecutePostWithHttpInfo
     *
     * Execute a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\DispatchPayoutResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentsPayoutPayoutIdActionsExecutePostWithHttpInfo($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'][0])
    {
        $request = $this->paymentsPayoutPayoutIdActionsExecutePostRequest($payoutId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\DispatchPayoutResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $request,
                        $response,
                    );
                
            }

            if ($this->responseWithinRangeCode('5XX', $statusCode)) {
                return $this->handleResponseWithDataType(
                    '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                    $request,
                    $response,
                );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\DispatchPayoutResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\DispatchPayoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                
            }
        
            if ($this->responseWithinRangeCode('5XX', $e->getCode())) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
                throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation paymentsPayoutPayoutIdActionsExecutePostAsync
     *
     * Execute a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentsPayoutPayoutIdActionsExecutePostAsync($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'][0])
    {
        return $this->paymentsPayoutPayoutIdActionsExecutePostAsyncWithHttpInfo($payoutId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentsPayoutPayoutIdActionsExecutePostAsyncWithHttpInfo
     *
     * Execute a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentsPayoutPayoutIdActionsExecutePostAsyncWithHttpInfo($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\DispatchPayoutResponse';
        $request = $this->paymentsPayoutPayoutIdActionsExecutePostRequest($payoutId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentsPayoutPayoutIdActionsExecutePost'
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function paymentsPayoutPayoutIdActionsExecutePostRequest($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdActionsExecutePost'][0])
    {

        // verify the required parameter 'payoutId' is set
        if ($payoutId === null || (is_array($payoutId) && count($payoutId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payoutId when calling paymentsPayoutPayoutIdActionsExecutePost'
            );
        }


        $resourcePath = '/payments/payout/{payoutId}/actions/execute';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($payoutId !== null) {
            $resourcePath = str_replace(
                '{' . 'payoutId' . '}',
                ObjectSerializer::toPathValue($payoutId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation paymentsPayoutPayoutIdGet
     *
     * Get the status of a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\PayoutResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse
     */
    public function paymentsPayoutPayoutIdGet($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdGet'][0])
    {
        list($response) = $this->paymentsPayoutPayoutIdGetWithHttpInfo($payoutId, $contentType);
        return $response;
    }

    /**
     * Operation paymentsPayoutPayoutIdGetWithHttpInfo
     *
     * Get the status of a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\PayoutResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentsPayoutPayoutIdGetWithHttpInfo($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdGet'][0])
    {
        $request = $this->paymentsPayoutPayoutIdGetRequest($payoutId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\PayoutResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $request,
                        $response,
                    );
                
            }

            if ($this->responseWithinRangeCode('5XX', $statusCode)) {
                return $this->handleResponseWithDataType(
                    '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                    $request,
                    $response,
                );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\PayoutResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\PayoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                
            }
        
            if ($this->responseWithinRangeCode('5XX', $e->getCode())) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
                throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation paymentsPayoutPayoutIdGetAsync
     *
     * Get the status of a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentsPayoutPayoutIdGetAsync($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdGet'][0])
    {
        return $this->paymentsPayoutPayoutIdGetAsyncWithHttpInfo($payoutId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentsPayoutPayoutIdGetAsyncWithHttpInfo
     *
     * Get the status of a payout instruction set
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentsPayoutPayoutIdGetAsyncWithHttpInfo($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdGet'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\PayoutResponse';
        $request = $this->paymentsPayoutPayoutIdGetRequest($payoutId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentsPayoutPayoutIdGet'
     *
     * @param  string $payoutId the payout id received from the creation of the payout instruction set (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function paymentsPayoutPayoutIdGetRequest($payoutId, string $contentType = self::contentTypes['paymentsPayoutPayoutIdGet'][0])
    {

        // verify the required parameter 'payoutId' is set
        if ($payoutId === null || (is_array($payoutId) && count($payoutId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payoutId when calling paymentsPayoutPayoutIdGet'
            );
        }


        $resourcePath = '/payments/payout/{payoutId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($payoutId !== null) {
            $resourcePath = str_replace(
                '{' . 'payoutId' . '}',
                ObjectSerializer::toPathValue($payoutId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation paymentsPayoutPost
     *
     * Create a payout instruction set
     *
     * @param  \Developerayo\FireblocksLaravel\Models\CreatePayoutRequest|null $createPayoutRequest createPayoutRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Developerayo\FireblocksLaravel\Models\PayoutResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse
     */
    public function paymentsPayoutPost($createPayoutRequest = null, string $contentType = self::contentTypes['paymentsPayoutPost'][0])
    {
        list($response) = $this->paymentsPayoutPostWithHttpInfo($createPayoutRequest, $contentType);
        return $response;
    }

    /**
     * Operation paymentsPayoutPostWithHttpInfo
     *
     * Create a payout instruction set
     *
     * @param  \Developerayo\FireblocksLaravel\Models\CreatePayoutRequest|null $createPayoutRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPost'] to see the possible values for this operation
     *
     * @throws \Developerayo\FireblocksLaravel\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Developerayo\FireblocksLaravel\Models\PayoutResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse|\Developerayo\FireblocksLaravel\Models\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentsPayoutPostWithHttpInfo($createPayoutRequest = null, string $contentType = self::contentTypes['paymentsPayoutPost'][0])
    {
        $request = $this->paymentsPayoutPostRequest($createPayoutRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\PayoutResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $request,
                        $response,
                    );
                
            }

            if ($this->responseWithinRangeCode('5XX', $statusCode)) {
                return $this->handleResponseWithDataType(
                    '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                    $request,
                    $response,
                );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Developerayo\FireblocksLaravel\Models\PayoutResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\PayoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                
            }
        
            if ($this->responseWithinRangeCode('5XX', $e->getCode())) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\Developerayo\FireblocksLaravel\Models\ErrorResponse',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
                throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation paymentsPayoutPostAsync
     *
     * Create a payout instruction set
     *
     * @param  \Developerayo\FireblocksLaravel\Models\CreatePayoutRequest|null $createPayoutRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentsPayoutPostAsync($createPayoutRequest = null, string $contentType = self::contentTypes['paymentsPayoutPost'][0])
    {
        return $this->paymentsPayoutPostAsyncWithHttpInfo($createPayoutRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentsPayoutPostAsyncWithHttpInfo
     *
     * Create a payout instruction set
     *
     * @param  \Developerayo\FireblocksLaravel\Models\CreatePayoutRequest|null $createPayoutRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentsPayoutPostAsyncWithHttpInfo($createPayoutRequest = null, string $contentType = self::contentTypes['paymentsPayoutPost'][0])
    {
        $returnType = '\Developerayo\FireblocksLaravel\Models\PayoutResponse';
        $request = $this->paymentsPayoutPostRequest($createPayoutRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentsPayoutPost'
     *
     * @param  \Developerayo\FireblocksLaravel\Models\CreatePayoutRequest|null $createPayoutRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentsPayoutPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function paymentsPayoutPostRequest($createPayoutRequest = null, string $contentType = self::contentTypes['paymentsPayoutPost'][0])
    {



        $resourcePath = '/payments/payout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createPayoutRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createPayoutRequest));
            } else {
                $httpBody = $createPayoutRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
